# This workflow will crawl InfoSys and look for version numbers on pages.
# It will save them in a mark down file and create a pull request

name: Crawl InfoSys

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore script/InfoSysCrawler.sln
    - name: Crawl infosys
      run: |
        dotnet run --project script/InfoSysCrawler.cli/InfoSysCrawler.cli.fsproj --path https://infosys.beckhoff.com/english/menu/menu.php?id=8644252870837316006 --markdown script/changelog_tc1xxx.md
        dotnet run --project script/InfoSysCrawler.cli/InfoSysCrawler.cli.fsproj --path https://infosys.beckhoff.com/english/menu/menu.php?id=8063276869205618704 --markdown script/changelog_plc_libraries.md
        git diff script/changelog_plc_libraries.md